### ISSUE TITLE
List Import Fails if (TMDB) id is "null"

### ISSUE THREAD

**Issue by sjdvda** [screeny05/letterboxd-list-radarr#1]
Thank you very much for this tool. I've been looking for something like this for a long time.

I tried to import my watchlist earlier and I had the following error:

`Unable to connect to list: Error converting value {null} to type 'System.Int32'. Path '[101].id', line 1, position 13816.`

Looking at the JSON file, it was because of the following entry: `{"id":null,"imdb_id":"tt0092337","title":"The Decalogue","release_year":"1989","clean_title":"/film/the-decalogue/","adult":false}`

Sidenote: This is probably because it is either listed as [a TV show](https://www.themoviedb.org/tv/42699-the-decalogue?language=en-US) or [10 different movies](https://www.themoviedb.org/search/movie?query=decalogue&language=en) on TMDB.

The only way I've been able to resolve the issue is by removing the item from my watchlist and waiting for the scraper to run again, then the import works fine. 

I see that the last commit was "remove series from output". Perhaps this could be further modified to also remove entries with a "null" id?

**Comment by screeny05** [comment]
This has been fixed in 34829a3

**Comment by sjdvda** [comment]
That was fast! Thank you very much.
