### ISSUE TITLE
"Lists tagged ‘[tag]’ by [user]" not working properly

### ISSUE THREAD

**Issue by azumukupoe** [screeny05/letterboxd-list-radarr#10]
fewer films are fetched when there should be more
> https://letterboxd.com/crew/tag/favorites/lists/
> https://letterbox-list-radarr.herokuapp.com/crew/tag/favorites/lists/
> 

> https://letterboxd.com/crew/tag/director/lists/
> https://letterbox-list-radarr.herokuapp.com/crew/tag/director/lists/
> 
not sure about this one

> https://letterboxd.com/crew/tag/showdown/lists/
> https://letterbox-list-radarr.herokuapp.com/crew/tag/showdown/lists/

**Comment by screeny05** [comment]
This has been added. Please feel free to try it.

If there's a problem, please don't hesitate to open a new issue.
