### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by JorgeSantosBravo** [screeny05/letterboxd-list-radarr#12]
I'm find that from a few days my watchlist stop sync.
I observe that the web ( https://letterbox-list-radarr.herokuapp.com/yuriaso/watchlist ) throws a blank page, so I think's there's something wrong with my watchlist, maybe I overexceded the limit of films?  

In developers tools I find this error: ERR_INCOMPLETE_CHUNKED_ENCODING.

Hope an asnwer, I like this tool very much!

**Comment by screeny05** [comment]
Duplicates #11
