### ISSUE TITLE
herokuapp to self-host

### ISSUE THREAD

**Issue by jun6lee** [screeny05/letterboxd-list-radarr#13]
I think we've recently been seeing a bit of downtime with Heroku app throwing this list into the failed status on radarr.
It does come back once in a while with manual intervention but is beginning to get tedious.

I really would like the functionality back, so had some very basic questions on the self-hosting aspect:

1: I have web hosting, can I. use that? It's a Linux install, but not a redis-instance specifically.
2. Could you share some specifics on a hosted install for a none techie?

Specifically:
-- Where what file are the REDIS_URL / PORT variable to be set?
-- What needs to be invoked/cronned for the local list to be updated on a self-hosted copy.

**Comment by jun6lee** [comment]
I am guessing another approach may be to put it on the same box as the radarr installation, but same questions apply.

**Comment by dbett4** [comment]
@jun6lee I was wondering if you ended up figuring how to self host. I'm looking into doing the same and don't know where to start.

**Comment by screeny05** [comment]
I elaborated on self-hosting in the readme.

There now is an option to use docker or the heroku deploy button, if you don't feel comfortable with docker or manual hosting.

Does this solve your issue?

**Comment by dbett4** [comment]
Thanks for the reply, screeny. I read the readme and could not find the environment variables. I also looked into docker and am still learning how to use it. I think it's over my head, so please don't feel like you have to help me out here.

I was using your script and it worked great until I upgraded to radarr V3. That's the only reason I was looking to self-host. Has anyone else had issues when upgrading to V3 and found a fix? I'd love to go back to using it just as it was before without having to self-host.

**Comment by dbett4** [comment]
I see you updated the readme. I'll check it out tonight. I appreciate your work here and donated to your paypal. Thanks again

**Comment by dbett4** [comment]
Latest updates fixed my issues. Thanks a lot!!

**Comment by jun6lee** [comment]
Thanks for the update on the ReadMe.
Heroku's "Account Verification Required" is crippling me for now.

I'll give self-hosting via docker a shot later and let you know if resolved for me.
