### ISSUE TITLE
Error when adding the list to Radarr

### ISSUE THREAD

**Issue by jweddy** [screeny05/letterboxd-list-radarr#15]
'Unable to connect to list, check the log for more details.'

this happens with every letterbox list, including the ones on the gitHub setup guide. 
everything worked fine until the update for Radarr came through, anyone else have these issues?

**Comment by saulsadman** [comment]
I am also having trouble, all my lists are broken! 

I also noticed the new update only has a single field for the list URL, whilst previously there were two fields. Also, the field for the API URL is gone, and the URL's themselves have been concatenated, e.g. 'https://letterbox-list-radarr.herokuapp.com/artorias/list/spaghetti-western/' 

Not sure what to do, beyond migrating my fam over to making Trakt lists as that seems to be supported natively.

**Comment by screeny05** [comment]
Which version of radarr are you using?

Does the problem still persist after the latest update (released about 10mins ago)?

**Comment by screeny05** [comment]
I've added usage instructions for radarr v3. That should fix your problem.
