### ISSUE TITLE
Why doesn't it fetch my watchlist? Does it have something to do with my username?

### ISSUE THREAD

**Issue by RelicCornhusk** [screeny05/letterboxd-list-radarr#26]
https://letterboxd.com/u_n_u_n_u_n/watchlist/

the link below doesn't provide any results https://letterbox-list-radarr.herokuapp.com/u_n_u_n_u_n/watchlist/

what am I doing wrong here?

**Comment by RelicCornhusk** [comment]
Found out, it works when putting my name in capital letters. don't know why that is required, it's not necessary when using letterboxd.com 

Also I set my username on Letterboxd with all letters lowercase. Anyways, glad it works. My bad for opening an issue for that.

**Comment by screeny05** [comment]
Seems to work woth all-lowercase now, too. I guess it was some kind of caching-issue
