### ISSUE TITLE
Heroku service is down (deleted/expired?)

### ISSUE THREAD

**Issue by gingerbeardman** [screeny05/letterboxd-list-radarr#34]
- https://letterbox-list-radarr.herokuapp.com
- "nothing is here"

I noticed this as my list had not updated for some time, for at least 4 or 5 months at this point.

Paging @screeny05

**Comment by gingerbeardman** [comment]
I'm now using self-hosted through docker, thanks for providing that!

a small related issue posted #35

**Comment by youridijk** [comment]
I’ve never seen the gerold URL before but in the readme there’s a URL hosted on render: https://letterboxd-list-radarr.onrender.com/

**Comment by gingerbeardman** [comment]
@youridijk seems it was changed from Heroku to Render in September 2022 
https://github.com/screeny05/letterboxd-list-radarr/commit/5818a88ecedb410212cf98e604189e28ff062a79

I missed that, so thanks! I guess there was no easy way to transition people?
