### ISSUE TITLE
Docker: screeny05/letterboxd-list-radarr:latest (not found)

### ISSUE THREAD

**Issue by gingerbeardman** [screeny05/letterboxd-list-radarr#35]
Docker complains that `screeny05/letterboxd-list-radarr:latest` cannot be not found

I edit the compose to grab `screeny05/letterboxd-list-radarr:1.0.1` specifically

**Comment by gingerbeardman** [comment]
it seems latest tag is not defined https://hub.docker.com/r/screeny05/letterboxd-list-radarr/tags

**Comment by screeny05** [comment]
I just pushed the latest tag. Should be working now.

**Comment by gingerbeardman** [comment]
thanks!
