### ISSUE TITLE
/films/popular not loading

### ISSUE THREAD

**Issue by ben-hudson** [screeny05/letterboxd-list-radarr#39]
Steps to reproduce:
1. Visit https://letterboxd-list-radarr.onrender.com/films/popular

Expected behaviour:
* List at https://letterboxd.com/films/popular is returned

Actual behaviour:
* Empty list is returned (i.e. `[]`)

**Comment by lotsokluze** [comment]
Director as well 

https://letterboxd-list-radarr.onrender.com/director/alfred-hitchcock/

**Comment by pmamberti** [comment]
Also seeing `/director/...` returning a `[]`
