### ISSUE TITLE
Doesn't update the list

### ISSUE THREAD

**Issue by rubbishgee** [screeny05/letterboxd-list-radarr#42]
It works perfectly when add a new list. 
but if I add a new movie and trigger a refresh, the new movie isn't added to Radarr.

**Comment by screeny05** [comment]
Movie lists are cached for 30 minutes. Have you waited a little bit before refreshing?

**Comment by rubbishgee** [comment]
Now it works! 
didn't know about the 30 minute caching, I triggered a new list update after a few hours and it worked flawless! Thank you!
