### ISSUE TITLE
Feature Enhancement: Rating/Review on Radarr is reflected on letterboxd

### ISSUE THREAD

**Issue by osamarao** [screeny05/letterboxd-list-radarr#45]
A Feature enhancement I think that would be really nice, is if we could rate on radarr and that is reflected on letterboxd. I'm guessing that'd need API access to letterboxd, which I don't know if they even give and if they did how much it'd cost, but lets consider it? 

Thanks

**Comment by osamarao** [comment]
Probably a Radarr plugin of sorts might be needed too.

**Comment by screeny05** [comment]
Yes, i think so as well. This list-provider is probably not the right place for a feature like this.
