### ISSUE TITLE
net import sync sometimes fails

### ISSUE THREAD

**Issue by azumukupoe** [screeny05/letterboxd-list-radarr#9]
Lot of my files got deleted during net import sync overnight and then I found out that the lists such as [this one](https://letterboxd.com//jbutts15/list/the-complete-criterion-collection/) aren't working anymore.
Update: it works now but I think bigger lists are unstable.
Update2: I just found that [this one](https://letterboxd.com//moulton/list/official-top-100-documentary-films/) not working so it might not be about the size after all.
https://web.archive.org/web/20200425210438/https://letterbox-list-radarr.herokuapp.com/moulton/list/official-top-100-documentary-films/

**Comment by screeny05** [comment]
Duplicate #11
